name: Update Docs
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git credentials
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Build docs
        run: npm run build:docs

      - name: Deploy to jeremyckahn.github.io/secure-file-transfer
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          single-commit: true
